apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoport-api
  labels:
    app: argoport-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argoport-api
  template:
    metadata:
      labels:
        app: argoport-api
    spec:
      containers:
        - name: argoport-api
          image: itaicodefresh/argoport-api:main
          ports:
            - containerPort: 2020
          env:
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github
                  key: username.txt
