apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoport-ui
  labels:
    app: argoport-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argoport-ui
  template:
    metadata:
      labels:
        app: argoport-ui
    spec:
      containers:
        - name: argoport-ui
          image: itaicodefresh/argoport-ui:main
          ports:
            - containerPort: 4200
